# Generated by Django 5.2.8 on 2025-12-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
