# Generated by Django 5.2.8 on 2025-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
